package com.cg.app.controller;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.cg.app.dto.InterestLog;
import com.cg.app.dto.Property;
import com.cg.app.dto.User;
import com.cg.app.services.PropertyService;
import com.cg.app.services.UserService;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /demo (after Application path)
public class RealEstateRestControllerApp {

	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserService userService;
	@Autowired
	private PropertyService propertyService;

	@PostMapping("/delete")
	void deleteUser(@RequestBody String userId) {
		userService.deleteUser(userId);
	}

	@PostMapping("/updateuser")
	User updateUser(@RequestBody User updateUser) {
		return userService.addUser(updateUser);
	}

	@PostMapping("/register")
	User newUser(@RequestBody User newUser) {
		return userService.addUser(newUser);
	}

	@GetMapping(path = "/alluserids")
	public @ResponseBody Iterable<String> getAllUserIds() {
		return userService.getAllUserIds();
	}

	@PostMapping(path = "/login")
	@ResponseBody User checkCredentials(@RequestBody String userId, @RequestBody String pass) {
		return userService.checkCredentials(userId, pass);
	}

	@GetMapping(path = "/allproperties")
	public @ResponseBody Iterable<Property> getAllPropertyList() {
		return propertyService.getAllProperty();
	}

	@GetMapping(value= "/getpropertybyid")
	public @ResponseBody Optional<Property> getPropertyById(@PathVariable("propId") String id) {
		return propertyService.getPropertyById(Integer.parseInt(id));
	}

	@GetMapping(value= "/getpropertybytype")
	public @ResponseBody List<Property> getPropertyByPropType(@PathVariable("propType") String propType) {
		return propertyService.getPropertyByType(propType);
	}

	@PostMapping("/addproperty")
	Property newProperty(@RequestBody Property newProperty) {
		return propertyService.addProperty(newProperty);
	}

	@PostMapping("/deleteproperty")
	public void deleteProperty(@RequestBody int propId) {
		propertyService.deleteProperty(propId);
	}

	@PostMapping("/addinterest")
	public void addInterest(@RequestBody InterestLog interest) {
		userService.addInterest(interest);
	}

	@GetMapping(path = "/allinterest")
	public @ResponseBody Iterable<InterestLog> getAllInterestList() {
		return userService.getInterestLists();
	}

}
